name: Flutter APK Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Reconstruct Project Safely
        run: |
          # 1. Itago muna ang totoong main.dart para hindi mabura ng flutter create
          mkdir -p temp_lib
          cp lib/main.dart temp_lib/main.dart
          
          # 2. Reconstruct safe android project files
          flutter create . --overwrite --org com.renantefullo --project-name tidal_stream
          
          # 3. Ibalik ang totoong code mo mula sa backup
          cp temp_lib/main.dart lib/main.dart

      - name: Build APK File
        run: |
          flutter pub get
          flutter build apk --release

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: TidalStream-RenanteFullo-APK
          path: build/app/outputs/flutter-apk/app-release.apk
